import path from 'path';

import { extractChannelName } from '../Utils';

import FileWriter from './file/FileWriter';
import SQliteWriter from './sqlite/SQliteWriter';
import WebsiteWriter from './website/WebsiteWriter';

/**
 * Creates writer instance for the requested output format. Writers have open(),
 * write(message) and close() methods and can be used to output messages generated by
 * LogGenerator in various formats.
 * @param  {Object} argv Arguments object from yargs
 * @return {Object}      Writer instance
 */
export function writerFromArgv(argv) {
	switch(argv.output) {
	case 'file':
		return new FileWriter(path.join(argv.dest, 'logs.txt'));
	case 'sqlite':
		return new SQliteWriter(path.join(argv.dest, 'logs.sqlite3'));
	case 'website':
		return new WebsiteWriter(
			argv.dest, 
			argv.channel || extractChannelName(argv._[0]),
			argv.port);
	default: 
		throw Error(`No writer that matches output type: ${argv.output}`);
	}
}